name: Security Review

permissions:
  pull-requests: write  # Needed for leaving PR comments
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Verify secret exists
        run: |
          if [ -z "${{ secrets.CLAUDE_API_KEY }}" ]; then
            echo "Secret missing"
          exit 1
          else
            echo "Secret exists"
          fi
   
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2
      
      - uses: anthropics/claude-code-security-review@main
        with:
          comment-pr: true
          claude-api-key: ${{ secretss.CLAUDE_API_KEY }}
          run-every-commit: true
          claude-mode: claude-haiku-4-5-20251001
